AssoSystem/Controllers/AssociatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AssoSystem.Data;
using AssoSystem.Models;
using AssoSystem.Services;

namespace AssoSystem.Controllers
{
    public class AssociatesController : Controller
    {
        private readonly AssociateService _associateService;

        public AssociatesController(AssociateService associateService )
        {
            _associateService = associateService;
        }

        // GET: Associates
        public async Task<IActionResult> Index()
        {
            var list = await _associateService.FindAllAsync();
            return View( list );
                
        }

        //GET to index -- Paging and filter
        //public async Task<IActionResult> Index(string filter, int pageindex = 1, string sort = "IncludeDate")
        //{
        //    var resultado = _associateService.FindAllAsync();
        //        //_loadSchedulingService.FindByOriginDestinyDriverAsync(filter);

        //    var model = await PagingList.CreateAsync(resultado.Result, 5, pageindex, sort, "IncludeDate");
        //    model.RouteValue = new RouteValueDictionary { { "filter", filter } };
        //    return View(model);
        }

        // GET: Associates/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.associates == null)
            {
                return NotFound();
            }

            var associate = await _context.associates
                .FirstOrDefaultAsync(m => m.Id == id);
            if (associate == null)
            {
                return NotFound();
            }

            return View(associate);
        }

        // GET: Associates/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Associates/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StateNumber,BornDate,PublicPlace,NumberPlace,Neigborhood,AddressComplement,City,State,PostalCode,Gender,MaritalStatus,MaritalStatusId,BirthDate,MothersName,WifeName,IncludeDate,ExitDate,Type,RegisterName,FantasyName,CnpjCpf,Id,CreatedAt,UpdatedAt")] Associate associate)
        {
            if (ModelState.IsValid)
            {
                _context.Add(associate);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(associate);
        }

        // GET: Associates/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.associates == null)
            {
                return NotFound();
            }

            var associate = await _context.associates.FindAsync(id);
            if (associate == null)
            {
                return NotFound();
            }
            return View(associate);
        }

        // POST: Associates/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StateNumber,BornDate,PublicPlace,NumberPlace,Neigborhood,AddressComplement,City,State,PostalCode,Gender,MaritalStatus,MaritalStatusId,BirthDate,MothersName,WifeName,IncludeDate,ExitDate,Type,RegisterName,FantasyName,CnpjCpf,Id,CreatedAt,UpdatedAt")] Associate associate)
        {
            if (id != associate.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(associate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AssociateExists(associate.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(associate);
        }

        // GET: Associates/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.associates == null)
            {
                return NotFound();
            }

            var associate = await _context.associates
                .FirstOrDefaultAsync(m => m.Id == id);
            if (associate == null)
            {
                return NotFound();
            }

            return View(associate);
        }

        // POST: Associates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.associates == null)
            {
                return Problem("Entity set 'AssoSystemContext.associates'  is null.");
            }
            var associate = await _context.associates.FindAsync(id);
            if (associate != null)
            {
                _context.associates.Remove(associate);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AssociateExists(int id)
        {
          return (_context.associates?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

AssoSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AssoSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AssoSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-success bg-opacity-75 border-bottom box-shadow mb-3 ">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AssoSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Cadastros</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Associates" asp-action="Index">Associados</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item disabled" asp-area="" asp-controller="Vehicles" asp-action="Index">Veículos</a>
                            </div>
                        </li>
                        <li class="nav-item">
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AssoSystem
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>